databases:
  - name: simple-email-verify-db
    plan: free
    region: frankfurt

services:
  - type: web
    name: simple-email-verify
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: simple-email-verify-db
          property: connectionString
